import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <h3> React Bootstrap </h3>
          <nav className="navigation">
            <Link className="home" href={"/"}>
              Home
            </Link>
            <Link className="home" href={"/form"}>
              Form
            </Link>
             <Link className="home" href={"/select"}>Select Menu</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
